[service]
name = "mi-aplicacion"
root = "./"

[deploy]
build = "npm install"
start = "node server.js"
env = ["NODE_ENV=production", "PORT=3000"]

[env]
PORT = "3000"
NODE_ENV = "production"
DATABASE_URL = "${{ DATABASE_URL }}"

[cron]
[[cron.jobs]]
schedule = "*/10 * * * *"
command = "npm run restart-app"

